site_name: CONTINUUM ATTEST - Documentation
site_url: https://attest.continuu.ms/
site_author: Ludovic FERNANDEZ, Alien6
site_description: >-
  Attest - Verifiable CI/CD Platform with cryptographic attestation - Public Documentation

# Repository
repo_name: Alien6-Studio/continuum-continuum-attest-www
repo_url: https://github.com/Alien6-Studio/continuum-attest-www

# Copyright
copyright: Copyright &copy; 2025 Alien6 Studio - CoopyrightCode Light License

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png
  palette:
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/logo.svg
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    #- toc.integrate

extra:
  generator: false
  social:
    - icon: fontawesome/regular/envelope
      name: send us an email
      link: mailto:contact@alien6.com
    - icon: fontawesome/brands/github
      link: https://github.com/Alien6-Studio/continuum-attest-www
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/Alien6-Studio/continuum-attest-www/issues" target="_blank" rel="noopener">feedback form</a>.

plugins:
  - search
  - minify:
      minify_html: true

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/feedback.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      title: "On this page"
      baselevel: 2
      separator: "_"
      toc_depth: 3

# Page tree
nav:
  - Home: index.md
  - Overview: overview.md
  - Getting Started:
    - Installation: installation.md
    - First Steps: first-steps.md
    - Core Concepts: concepts.md
  - User Guide:
    - Pipeline Configuration: pipeline-configuration.md
    - Command Line Interface: cli.md
    - Attestation & Signatures: attestation.md
    - Cache & Performance: cache-performance.md
  - Advanced Topics:
    - GitOps & Kubernetes: gitops.md
    - Policies & Governance: policies.md
    - CI/CD Interoperability: interoperability.md
    - Monitoring & Observability: monitoring.md
  - Practical Applications:
    - Examples & Use Cases: examples.md
    - Migration Guide: migration.md
    - Enterprise Setup: enterprise.md
    - Troubleshooting: troubleshooting.md
  - Reference:
    - API & SDK: api.md
    - Pipeline Format: pipeline-format.md
    - FAQ: faq.md
    - Glossary: glossary.md